### ISSUE TITLE
bad look close button in overview mode

### ISSUE THREAD

**Issue by wep777** [monday15/lounge-gtk-theme#10]
![Screenshot from 2019-04-16 22-46-49](https://user-images.githubusercontent.com/16454901/56235968-96eeb580-6099-11e9-8166-831a99f3407c.png)

**Comment by monday15** [comment]
What distro do you use?  Gnome-shell version?

**Comment by monday15** [comment]
Also, if you've downloaded theme from opendesktop, what archive did you choose?

**Comment by monday15** [comment]
What gnome-shell version do you have? (you can check it by running `gnome-shell --version` from terminal). What icon-theme do you use? If you've downloaded already builded theme from opendesktop, what archive did you choose?

**Comment by wep777** [comment]
Gnome Shell version 3.32
Distro - Manjaro (DE - Gnome)
download link : https://github.com/monday15/lounge-gtk-theme/archive/1.18.tar.gz (then run build&install command from root user in terminal)
icon-theme - Paper

**Comment by monday15** [comment]
Thanks for info!
I cant reproduce this bug in fully-updated Manjaro VM with Paper icon theme (used this one -  https://github.com/snwh/paper-icon-theme - is that the one you are using?). I've tried both xorg and wayland sessions with different screen resolutions - no issues.

I think the bug can be somehow related to video-driver you are using, but in that case, it should also appear on "Default" gnome-shell theme. Try changing gnome-shell theme to "Default" and see if it will occurs.

**Comment by wep777** [comment]
> bug can be somehow related to video-driver you are using

i use intel hd 620 video card

> Try changing gnome-shell theme to "Default" and see if it will occurs.

this bug appears only in lounge shell theme =(

**Comment by monday15** [comment]
Ok, I've check difference against upstream, looks like shadow causes this.  
Can you, please, test this files and see if buttons will work ok with them?  
If first variant will work, no need to test others.

You need to override `/usr/share/themes/Lounge/gnome-shell/gnome-shell.css` file, with each of this files (just rename them to gnome-shell.css), one by one (or you can just copy content - open existing gnome-shell.css, select all text and override it with new file content). After overriding you need to run this command
```
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval 'Main.loadTheme();'
``` 
to reload gnome-shell theme (you can also do it by switching theme to another in gnome-tweaks, and enabling Lounge again). 

Files:
variant 1
[gnome-shell.css2nospread.txt](https://github.com/monday15/lounge-gtk-theme/files/3093740/gnome-shell.css2nospread.txt)
If it works fine, no need to test others.

variant 2
[gnome-shell.css3nospread50percent.txt](https://github.com/monday15/lounge-gtk-theme/files/3093741/gnome-shell.css3nospread50percent.txt)

variant 3
[gnome-shell.css1noboxshadow.txt](https://github.com/monday15/lounge-gtk-theme/files/3093739/gnome-shell.css1noboxshadow.txt)

**Comment by wep777** [comment]
> variant 3

solved the problem
thank you!

**Comment by monday15** [comment]
@wep777, hey! in case you're still on Manjaro with the same video card, please, check again, variant 1 or 2. There were changes in gnome-shell, related to this issue and if shadow on window close button will work ok, I can return it to the theme.

Just make sure you have lastest gnome-shell from repos (something like 3.34.1).
