### ISSUE TITLE
xfce4 elements are dark in the light theme variant

### ISSUE THREAD

**Issue by foresto** [monday15/lounge-gtk-theme#12]
The xfce panel, alt-tab switcher, and mailwatch panel plugin (and probably some other plugins) are dark, even in the light theme variant. This not only looks strange, but also makes some items (e.g. icon sets intended for light themes) difficult to see.

The workspace switcher also looks wrong in the light variant, with such low contrast between its rectangles that it's sometimes difficult to see them.

**Comment by monday15** [comment]
Thanks for report!

> The xfce panel, alt-tab switcher, and mailwatch panel plugin (and probably some other plugins) are dark, even in the light theme variant.

This is intended, but I see you point. Most weird thing is white menus appearing from dark panel buttons. I'll see what I can do.

> This not only looks strange, but also makes some items (e.g. icon sets intended for light themes) difficult to see.

Hmmm, this is strange. I'll test this more closely, I think icons that are used on the panel should be symbolic and they inherit a color from panel's elements text color (or something like that). 

What xfce version do you use?

**Comment by foresto** [comment]
Xfce 4.12.

> I think icons that are used on the panel should be symbolic and they inherit a color from panel's elements text color (or something like that).

That is an approach that some themes take, but not all. I use the Tango icon theme. Here's my panel volume control:

![Screenshot_2019-09-22_22-24-18](https://user-images.githubusercontent.com/322134/65403710-f6a86580-dd89-11e9-9a6f-dd583c8241b7.png)

See those blue sound waves? Those indicate the volume level: more are drawn when it's louder, fewer when it's quieter. Easy and clear.

Now, here's how it looks with a dark panel:

![Screenshot_2019-09-22_22-24-34](https://user-images.githubusercontent.com/322134/65403733-1c356f00-dd8a-11e9-9a0e-b1ed6385bda1.png)

Some of the speaker's shape-defining outline disappears into the darkness, leaving a more rudimentary, ugly appearance. More importantly, it's difficult to see the volume level there. Nearly impossible when there are a bunch of white windows on screen.

**Comment by foresto** [comment]
I've been making some tweaks to a local copy of the theme to try to make it meet my needs. I can share when I get a bit further, in case it helps inspire ideas. (I'm not sure how far I'll get, though, since I have little experience in gtk theme development.)

**Comment by monday15** [comment]
I've made some adjustments, please, test. Use git clone and build or use this archive with prebuilded theme [lounge-121-xfce-sway-default.zip](https://github.com/monday15/lounge-gtk-theme/files/3655363/lounge-121-xfce-sway-default.zip). If you don't mind, also check adjusted workspace switcher in dark theme.

Comments like this are very much appreciated:
> The workspace switcher also looks wrong in the light variant, with such low contrast between its rectangles that it's sometimes difficult to see them.

Thanks for your help in improving the theme!

**Comment by foresto** [comment]
Much improved! All my panel icons are now easy to read. The Alt+Tab task switch window also looks much better. Thanks!

Any particular reason for making xfce_panel_bg_color #e2e2e2? It's darker than I expect next to other windows, and I see gtk3-colors.scss uses #eeeeee. The currently selected task button seems a little dark, too, perhaps because the near-black text starts to lose contrast against that background color. (These issues are minor, though; I can live with them.)

![Screenshot_2019-09-27_13-43-06](https://user-images.githubusercontent.com/322134/65802018-4d69c280-e12f-11e9-9f42-169902c8e958.png)

The workspace switcher looks better, too. The blue selection color clarifies which workspace is active, especially when only two workspaces are present and there would otherwise be no direct way to tell whether the darker one or the lighter one was active. The thin blue borders don't stand out much, especially in the dark theme, but maybe that's not such a big deal.

Have you considered using blue on the background instead of the borders? This would make it visible even when the active workspace contains no windows, and would make it more obvious in other cases. I started experimenting with this idea in the light theme, like so:

![Screenshot_2019-09-27_13-43-21](https://user-images.githubusercontent.com/322134/65802814-a0447980-e131-11e9-8c4a-498171584009.png)

**Comment by foresto** [comment]
> Comments like this are very much appreciated:

> Thanks for your help in improving the theme!

Thanks for saying so. There are quite a few people out there who seem to view bug reports as personal attacks instead of contributions, or don't appreciate how much time it takes to troubleshoot/analyze/clearly describe a problem. It's refreshing to get a positive response.

**Comment by monday15** [comment]
> Any particular reason for making xfce_panel_bg_color #e2e2e2?

Color difference between windows and panel. Yep, maybe #e2 is too much, further adjustments incoming.

> Have you considered using blue on the background instead of the borders? This would make it visible even when the active workspace contains no windows, and would make it more obvious in other cases.

I've tried it, and I didn't like empty workspace indication, from my point of view it is too bright/disturbing "hey, I'm lightblue rectangle, look at me". But I like screenshot with your adjustments much more, lightblue windows on the switcher looks way better and "normal" (while just lightblue borders are a bit "wierd"). Adjustments incoming.

And thank you for a kind words!

**Comment by monday15** [comment]
Panel background color is #e9e9e9 now and workspace switcher looks less weird.

Thanks for your comments and suggestions!
