### ISSUE TITLE
Black margin around scroll bars in liferea internal web browser

### ISSUE THREAD

**Issue by foresto** [monday15/lounge-gtk-theme#13]
Scroll bars in Liferea's internal web browser (libwebkit2gtk I think) are surrounded by black margins. (Tested on Xubuntu 19.04, WM compositing off.)

![Screenshot_2019-09-23_13-04-39](https://user-images.githubusercontent.com/322134/65458893-82aaa380-de03-11e9-8a06-a3e44b3674eb.png)

**Comment by monday15** [comment]
Thanks for reporting an issue!
