### ISSUE TITLE
Unreadable text in Gnome-shell

### ISSUE THREAD

**Issue by ghost** [monday15/lounge-gtk-theme#15]
Hi, as the title say, that's the situation. Gnome 3.34.1 - The distro is Manjaro

![Schermata da 2019-11-01 10-25-01](https://user-images.githubusercontent.com/20545323/68015297-25233580-fc92-11e9-80af-0e9fd2610166.png)
![Schermata da 2019-11-01 10-25-27](https://user-images.githubusercontent.com/20545323/68015449-7cc1a100-fc92-11e9-8e17-19ac5cdb3b9b.png)

**Comment by monday15** [comment]
Thanks for reporting an issue!
I was unable to reproduce this bug in manjaro vm (fully updated). Probably it is related to video drivers.

What is you video card manufacturer (amd/nvidia/intel)? How do you install Lounge theme (build yourself, download prebuilded package, something else)?

Also, please, download prebuilded theme archive for GNOME 3.32 (yep, one release older) from here https://www.pling.com/p/1258756/ (you need to open files tab, right under a screenshot) and try to reproduce the bug with it (new hack was added to gnome-shell theme 3.34, it can be the source of this bug). 

You'll need to replace your current `/usr/share/Lounge/gnome-shell` (or `~/.themes/Lounge/gnome-shell`) with `Lounge/gnome-shell` folder from the archive. After that you'll need to reload gnome-shell theme (on wayland session you can do it by changing gnome-shell theme to another theme and then switching back to Lounge).

**Comment by ghost** [comment]
Hi and thanks for the answer. I've got an NVIDIA GeForce GTX 650, driver version: 435.
I've download Lounge from Github and compiled by miself, but i also tried the package from gnome-look. Same result, even with the 3.32 version. The gtk theme looks perfect, the problem is only on the shell. Now I try the flatpak

**Comment by monday15** [comment]
> Now I try the flatpak

Flatpak doesn't support gnome-shell themes.

Unfortunately, I dont have a pc with NVIDIA card. I'll take a closer look at changes (compare to default gnome-shell theme), may be I'll find something. I assume default and other themes works fine?

**Comment by ghost** [comment]
I have a lot of theme installed. Plata, Materia, Matcha, Adwaita etc work perfectly. But I have to admit that this is not the first time I have this kind of issue with the shell themes. Some themes have the same problem with the text. I really don't know if it's a problem with my drivers (in general, they don't give me problems). Thanks anyway, I'll keep an eye on the Lounge updates :-)

**Comment by monday15** [comment]
Please, try this gnome-shell.css file (replace extisting gnome-shell.css file in `Lounge/gnome-shell` and reload gnome-shell theme).

[gnome-shell.zip](https://github.com/monday15/lounge-gtk-theme/files/3800353/gnome-shell.zip)

**Comment by ghost** [comment]
Wait, I reinstalled the theme again by replaying it from github, because I had deleted version 3.32. Now it works perfectly! I didn't try the file you sent me. No more need. Thank you so much for your support :-)

**Comment by monday15** [comment]
@ginwsby most likely, that's because I've also pushed this change to master branch 10-15 minutes ago))) 

Anyway, thanks for you help! There was an actual issue in the theme.

**Comment by ghost** [comment]
Oh, perfect! Thanks a lot man!
