### ISSUE TITLE
Change colour of sliders in gnome shell

### ISSUE THREAD

**Issue by mthomos** [monday15/lounge-gtk-theme#16]
![image](https://user-images.githubusercontent.com/29919666/68089986-527d0880-fe77-11e9-8642-8345162a8977.png)

Can you change the colours of these sliders to from gray to theme accent ?

**Comment by monday15** [comment]
Looks like a good a idea for theme built with fancy scale style. Yep, I'll add this option.

**Comment by mthomos** [comment]
BTW, i use your theme with with prime and fancy style and i like it a lot. Maybe make it the default build option as it is closer to the aesthetics of Adwaita

**Comment by monday15** [comment]
Yes, fancy style looks more classic and familiar and, probably, more suitable for the most of people. But I'll keep casual style as default one -  it gives the theme unique look, even though sometimes white scales doesn't work very well  (they are barely visible on gimp launch banner and in easytag app). No hard feelings.
