### ISSUE TITLE
gtk2: Add dark theme

### ISSUE THREAD

**Issue by wangxa** [monday15/lounge-gtk-theme#3]
I had tried this theme. I like it. 

Could you develop a dark version, especially for the applications which are using Gtk2, like audacious, dia, inkscape, etc.?

**Comment by monday15** [comment]
Thanks for feedback! First, I need to polish gtk3 dark theme, then I can make one for gtk2. It may take a week or two.

**Comment by monday15** [comment]
Done, check release 1.0. 
https://github.com/monday15/lounge-gtk-theme/releases/tag/1.0

**Comment by wangxa** [comment]
Thank you very much.
