### ISSUE TITLE
[Request] Flat variant

### ISSUE THREAD

**Issue by pkomur** [monday15/lounge-gtk-theme#4]
The theme is great, but please consider creating a flat variant.

**Comment by monday15** [comment]
Thanks! By flat you mean no shadows on buttons/switches (cant remember any un-flat elements except those)? I'll think about it, but cant promise anything - making theme flat is relatively easy, but maintaining both variants can be too complicated.

**Comment by monday15** [comment]
@pkomur please, check version 1.6 - I simplified some widgets (buttons, switches, bars) - theme looks more flat now.

Feel free to reopen if you not satisfied with current flatness.
