### ISSUE TITLE
[request] Slim version

### ISSUE THREAD

**Issue by ermo** [monday15/lounge-gtk-theme#5]
For Adwaita, godlyranchdressing created a tweaked [Adwaita-Slim](https://github.com/godlyranchdressing/Adwaita-Slim) theme which just slims down the excessive padding without changing anything else in the original Adwaita theme.

Would you be open to releasing a similar Lounge-Slim version alongside the original version?

**Comment by monday15** [comment]
@ermo  Hmmm, I thought Lounge is already slim)) Anyway, i saw Adwaita-slim screenshot, and I think it will be easy to make slimer variant. I'll look into it after some testing/polishing theme with recently updated color scheme. Probably, next week.

**Comment by ermo** [comment]
I don't know if you use Xfce, but if you do, try adding a new tab to an xfce4-terminal window using Adwaita-Slim and then try it in lounge and you'll get a good feeling of the difference in how much vertical space is taken up?

**Comment by monday15** [comment]
@ermo Thanks to you, i managed to fix an issue with gnome-terminal (it also has too big tab bar, not matching gedit/nautilus). Meanwhile, I found out that xfce4-terminal has it own logic of drawing tab bar, I tried to change some things, but xfce4-terminal's tab bar doesn't match regular gtk3 one.

Good news is xfce4-terminal has "slim tabs" option - you can find it in menu: Edit > Preferences > Appearance > Tabs > Use custom styling to make tabs slim.

**Comment by monday15** [comment]
I tried some padding changes, didn't like the result, plus, it creates inconsistency in headerbars (some of them uses 2 lines of text, others - custom-size buttons). I won't provide/maintain slim variant, but issue will be open, in case someone will make a slim fork.

**Comment by berkiyo** [comment]
Strange. I found Lounge to be quite pleasant and slim compared to Adwaita. I think there is absolutely no reason for it to be any slimmer other wise it may look strange on displays with higher pixel densities. In its current state, Lounge is a really balanced theme.

Also, I really love the changes you made with version 1.11. Keep up the great work!

**Comment by monday15** [comment]
Closed, WONTFIX.
