### ISSUE TITLE
[request] Gnome-shell night theme

### ISSUE THREAD

**Issue by marlomjobsom** [monday15/lounge-gtk-theme#6]
Hello @monday15 .
Firstly congrats for this theme. I am really enjoying it!

I would like to ask you to also add the night version for gnome-shell as well.
When I installed it, I realized the gnome-shell only got the "light" one, while the windows got both, light and night versions.

**Comment by monday15** [comment]
Glad you like it! Yeah, that's a good idea to make darker version of shell theme so window colors in dark theme will not interfuse with shell interface colors. It will take some time.

**Comment by monday15** [comment]
I've added test version of dark theme to 1.10 release, it works ok, but requires more tweaks here and there. I've tested Lounge-night theme with new dark shell theme, and I don't think it worth the effort. Regular Lounge gnome-shell theme works ok, and I don't see any usability issues with similar colors in gtk/shell themes. Only thing I really like about new dark theme is inverted colors in workspace switcher - they works a bit better with dark windows, but it is just small detail.

So, currently, I want to play a bit more with it on holidays, and, if there will be no significant improvements over regular theme - I'll just drop it (maintaining only one theme will be easier). Current version still will be available via 1.10 release.

**Comment by marlomjobsom** [comment]
Nice you could check this out so quickly.
I just downloaded and build again the lounge-gtk-theme and I am using the night version on gnome-shell.

It appear to be the case that it's just minor details, not that much significant. However, I noticed the drop menu background-color in gnome-shell is a little bit darker than the regular one. It's better than the regular one, _in my own opition_.
But, as you said, it's just a very small details.

*Suggestions*
* Consider taking in count this new background-color to the regular gnome-shell theme, If will be the case to keep only the regular version.
* How about to set the border-line of the drops menus of gnome-shell darker than its background-color?

**Comment by monday15** [comment]
>    Consider taking in count this new background-color to the regular gnome-shell theme, If will be the case to keep only the regular version.

That won't happen, I dont like how shell's darker background blends with light gtk theme.
>    How about to set the border-line of the drops menus of gnome-shell darker than its background-color?

I've tried that (in default gnome-shell theme they was dark) and came to conclusion, that with light borders it's easier to focus on appeared menu. 
But, you can do it by changing __$borders_color__ to hex-color code __#000000__ in this line, iirc. Just rebuild theme after this.
https://github.com/monday15/lounge-gtk-theme/blob/f47db74c19ded93b090b6cf7068ff47719dbcf4f/src/gnome-shell/_common-shell.scss#L541

**Comment by monday15** [comment]
@marlom-jobsom dark borders for menus and some other widgets (volume indicator, appswitcher) was a good idea, thanks!

**Comment by monday15** [comment]
Closed. Dark gnome-shell theme dropped since 1.11.
If you need darker theme, try other shell themes.
