### ISSUE TITLE
gtk3: LibreOffice tabs are hard to read

### ISSUE THREAD

**Issue by berkiyo** [monday15/lounge-gtk-theme#8]
Hello,

I have found another problem which is maybe worth looking into. When using the ribbon UI in LibreOffice, it isn't easy to see which option you selected as there is no indicator. Adwaita has a blue indicator while Arc uses a whole tab. Having a blue indicator like Adwaita's or similar accent found in Lounge might be nice.

Here is what LibreOffice shows with Lounge:
![libreoffice-lounge](https://user-images.githubusercontent.com/38805550/51777258-60676580-2150-11e9-91ef-aac3a4fdc32d.png)

With Adwaita:
![libreoffice-adwaita](https://user-images.githubusercontent.com/38805550/51777268-6d845480-2150-11e9-88c8-e5222d70ac6a.png)

With Arc:
![libreoffice-arc](https://user-images.githubusercontent.com/38805550/51777273-7543f900-2150-11e9-8da7-21ffd3f78fd2.png)

If you want to take a look at LibreOffice with this mode, you need to do the following:

1. **"Tools" -> "Options"** (ALT+F12) -> "Advanced"
2. Enable "Enable Experimental Features (may be unstable)
3. Restart LibreOffice
4. Then, Click on: "**View" -> "User Interface"** and select "Tabbed"

**Comment by monday15** [comment]
Thanks for very detailed bug report! 
I assume, you're using copr repo package, it will be updated approximately this Saturday with 1.12 release.
Fixed in https://github.com/monday15/lounge-gtk-theme/commit/7544fa2c515429eb4a5baaedbb388a7b64797cfe.
