### ISSUE TITLE
Screenshots and 1 request.

### ISSUE THREAD

**Issue by freefreeno** [monday15/lounge-gtk-theme#9]
This is your theme with a different xfwm4 theme that I stole from another theme and it fits perfect in my eyes.The color is off just a hair. Other than just showing the xfwm4 theme I was wondering if you meant to leave the desktop icons with the background shadow that is visible. You will see what I am talking about in screen shots. This is newaita icons which comes in two icon sets, one for light and one for dark and each can be changed colors to like 4 different colors. This is one of my favorite themes now that I have found this xfwm4 theme.
![screenshot_2019-03-02_16-28-57](https://user-images.githubusercontent.com/41884680/53688420-40a3fe00-3d09-11e9-9c96-09201277ca4d.png)
![screenshot_2019-03-02_16-24-56](https://user-images.githubusercontent.com/41884680/53688422-43065800-3d09-11e9-8eaa-df6300014af9.png)
![screenshot_2019-03-02_16-24-42](https://user-images.githubusercontent.com/41884680/53688425-47327580-3d09-11e9-8b67-5c82da28b543.png)
 I love this theme I just wish I new how to change the color of .xmp files without losing there fade and all that so I could adjust this xfwm4 to perfect color. It tries to pick the colors up from the theme but it doesn't match all the way.

**Comment by monday15** [comment]
Thanks for feedback!
> I was wondering if you meant to leave the desktop icons with the background shadow that is visible.

I don't remember, and yeah, it looks a bit out of place. I'll check it out.

> I love this theme I just wish I new how to change the color of .xmp files without losing there fade and all that so I could adjust this xfwm4 to perfect color. It tries to pick the colors up from the theme but it doesn't match all the way.

I don't know how xmp works, but you could try modify lounge xfwm4 theme for you needs - just go to xfwm4-dark folder. You need to open xfwm4-assets.svg, change assets colors/size/whatever and re-render images using xfwm4-render-assets.sh script. Also, there is `themerc` file in that folder with some settings (like padding between titlebar edge and buttons).

**Comment by freefreeno** [comment]
I think what is throwing me off about your xfwm4 is the fact that it has that distinct line that separates it from the main thunar window and it is a little to tall. Maybe try to take the separation line out of it and reduce the tallness of it by 1/4 because really for xfce users we don't care if it matches regular gtk or not as long as it looks good in thunar. These are just my ideas. I like rounded corners in mine but just to remove the line and reduce it's tallness I think would make a huge difference.Over all there is not much of a better looking theme out there. Performance is good with this theme also. I wish I could do what you do. By the way I am running Arch xfce with gtk 3.24.5. Just my ideas so don't think I don't like it because i love it especially how clean it looks and how smooth my little Arch machine runs with it.

**Comment by freefreeno** [comment]
I made this xfwm4 from another theme to match and I also made one one exactly like yours but changes the color to the exact color of the top of thunar.
This is yours that I changes the colors on.

![screenshot_2019-03-04_00-23-11](https://user-images.githubusercontent.com/41884680/53714376-be543080-3e13-11e9-9358-ad06e6d835c9.png)

This is the one I made from another theme. I like this one.
![screenshot_2019-03-04_00-24-41](https://user-images.githubusercontent.com/41884680/53714433-ee033880-3e13-11e9-9466-b8eabb57c1ab.png)

I fixed the icon shadows on the desktop. Add this to the xfce.rc file at the bottom.
widget_class "*XfdesktopIconView*"                    style "xfdesktop-icon-view"

And this.
style "xfdesktop-icon-view" {
  XfdesktopIconView::label-alpha = 0
  XfdesktopIconView::selected-label-alpha = 100
  XfdesktopIconView::shadow-x-offset = 0
  XfdesktopIconView::shadow-y-offset = 1
  XfdesktopIconView::selected-shadow-x-offset = 0
  XfdesktopIconView::selected-shadow-y-offset = 1
  XfdesktopIconView::shadow-color = "#000000"
  XfdesktopIconView::selected-shadow-color = "#000000"
  XfdesktopIconView::shadow-blur-radius = 2
  XfdesktopIconView::cell-spacing = 2
  XfdesktopIconView::cell-padding = 6
  XfdesktopIconView::cell-text-width-proportion = 1.9

  fg[NORMAL] = @selected_fg_color
  fg[ACTIVE] = @selected_fg_color
}

**Comment by monday15** [comment]
I've looked at desktop icons with the other themes (Arc, Greybird) and I dont like how they looks on light wallpapers. Current variant readability is much better.

![xf1](https://user-images.githubusercontent.com/42862490/53963551-5c474400-410f-11e9-826b-ffa306b7b4d8.png)     ![xf2](https://user-images.githubusercontent.com/42862490/53963552-5cdfda80-410f-11e9-8e17-5bd3f9a1871b.png)

> Maybe try to take the separation line out of it and reduce the tallness of it by 1/4 because really for xfce users we don't care if it matches regular gtk or not as long as it looks good in thunar.

Removing separation line and reducing titlebar height will also require changing style of close/minimize/etc buttons and headerbar color in gtk3-apps, I pass. Main idea was to make them maching gtk3 titlebars in gnome, to prevent possible inconsistency.

 ![xf4](https://user-images.githubusercontent.com/42862490/53963554-5cdfda80-410f-11e9-83fc-2c985e0ec0de.png)

> rounded corners

I also prefer more rounded corners, but they look ugly in light theme (pixelated), so I had to reduce roundness to minimum. I hope xfce developers will find a better realisation of rounded corners in the future.

Anyway, thanks for sharing you thoughts.

**Comment by freefreeno** [comment]
Its ok I will just add the -
style "xfdesktop-icon-view" {
  XfdesktopIconView::label-alpha = 0
  XfdesktopIconView::selected-label-alpha = 100
  XfdesktopIconView::shadow-x-offset = 0
  XfdesktopIconView::shadow-y-offset = 1
  XfdesktopIconView::selected-shadow-x-offset = 0
  XfdesktopIconView::selected-shadow-y-offset = 1
  XfdesktopIconView::shadow-color = "#000000"
  XfdesktopIconView::selected-shadow-color = "#000000"
  XfdesktopIconView::shadow-blur-radius = 2
  XfdesktopIconView::cell-spacing = 2
  XfdesktopIconView::cell-padding = 6
  XfdesktopIconView::cell-text-width-proportion = 1.9

  fg[NORMAL] = @selected_fg_color
  fg[ACTIVE] = @selected_fg_color
}
(and the )
widget_class "*XfdesktopIconView*"                    style "xfdesktop-icon-view"
to the xfce.rc file.
At first I was wrong. I had it added in two places but it simply that right there added to your xfce.rc file that does all I need it too. I do not like white shadows on desktop.
So even on dark themes you like shadows behind the desktop icons. I haven't seen a theme purposely left like that in 10 years. And for light version the settings have to be changed in the above just a little. Its all in the Arch wiki and OF COURSE IT IS JUST PERSONAL PREFERENCE. Thanks for listening. The xfwm4 I am using is not the one I made because of the corners being like that but the one I am using and about to match to it looks awesome with not blurry corners. People can just remove the shadows themselves.

![screenshot_2019-03-07_12-20-11](https://user-images.githubusercontent.com/41884680/53979424-6e0af600-40d3-11e9-933e-746971967063.png)
